language: c

compiler:
 - clang
 - gcc

before_script:
 - git submodule init
 - git submodule update
 - ./autogen.sh

script:
 - ./configure
 - make

env:
  global:
    - secure: "aiYevMw0lXG2RcjsqQ5WaBSoik13QSjt24lKZJrjcVLQpW63G+xkOyDj3INCBtSfHYH6su9/HU0XUkFcjFkhZmBgHjOjJjcau4Ksw6CgyhjdqK3qIAQsW/g8/PybXUQlP6LYUBcUZPwjjvHCuO+9rJQ+fwUqbIdSxy1eyZM0TeY="

addons:
  coverity_scan:
    project:
      name: "clowwindy/ShadowVPN"
      description: "ShadowVPN"
      notification_email: clowwindy42@gmail.com
      build_command_prepend: "git submodule init; git submodule update; ./autogen.sh ; ./configure"
      build_command: "make -j4"
      branch_pattern: coverity_scan
